default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lunch_project_development

test:
  <<: *default
  database: lunch_project_test

production:
  <<: *default
  database: lunch_project_production
  username: lunch_project
  password: <%= ENV['LUNCH_PROJECT_DATABASE_PASSWORD'] %>
