name: Ruby on Rails Rspec Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWROD: postgres 
          POSTGRES_DB: postgres
        ports: 
          - 5432/tcp
    steps:
    - name: Checkpit repository
      uses: actions/checkout@v2

    - name: Install ruby version
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    
    - name: Install Postgres client
      run: sudo apt-get install libpq-dev -y

    - name: Create database
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWROD: postgres
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:setup
        yarn install --check-files
        bundle exec rails webpacker:compile
        
    - name: Run tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWROD: postgres
      run: rspec
